<a href="https://colab.research.google.com/github/lurwan2107/ArewaDS_DeepLearning/blob/main/00_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Improting and checking version of PyTorch
import torch
torch.__version__

'2.1.0+cu121'

In [ ]:
# Scalar
Scalar = torch.tensor(7)
Scalar

tensor(7)

In [ ]:
# Checking the dimesion
Scalar.ndim

0

In [ ]:
# Get the pyhton number within a tensor (works only with one-element tensor)
Scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [ ]:
# Cehck the dimension of the vector
vector.ndim

1

In [ ]:
# checking the shape of the vector
print(vector.shape)
print(len(vector))

torch.Size([2])
2


In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Checking the dimension
MATRIX.ndim

2

In [ ]:
# Checking the shape
MATRIX.shape

torch.Size([2, 2])

In [ ]:
print(len(MATRIX))

2


In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
# Checking the dimension
TENSOR.ndim

3

In [ ]:
# Checking the shape
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# Creating a random tensor of size(3, 4)
random_tensor = torch.rand(size=(3, 4))
print(random_tensor, random_tensor.dtype)

tensor([[0.5268, 0.3705, 0.1480, 0.0840],
        [0.5034, 0.5131, 0.2869, 0.6258],
        [0.5809, 0.1362, 0.9304, 0.2655]]) torch.float32


In [ ]:
# Creating random tensor of size(224, 224, 3)
random_tensor_image = torch.rand(size=([224, 224, 3]))
print(random_tensor_image.shape, random_tensor_image.ndim)

torch.Size([224, 224, 3]) 3


In [ ]:
# Create tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Create tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
# Use torch.arange(), torch.range() is deprected
zero_to_ten_deprecated = torch.range(0, 10)
zero_to_ten = torch.arange(0, 20, 2)
zero_to_ten_deprecated, zero_to_ten

<ipython-input-19-761bf42a315b>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]))

### Tensor datatypes

In [ ]:
# Default dataype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,  # Default to None, which is torch.flat32 or whatever datatype passed.
                                device=None,  # defaults to None, which uses the default tensor datatype.
                                requires_grad=False) # if True, operatin performed on the tensor are recorded.
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([5, 6], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
# Find out details about it
print(some_tensor)
print(f"The shape of tensor is: {some_tensor.shape}")
print(f"Datatype of tensor is: {some_tensor.dtype}")
print(f"Device which tensor is stored on: {some_tensor.device}")

tensor([[0.0218, 0.7673, 0.0477, 0.5630],
        [0.4301, 0.3886, 0.8149, 0.8823],
        [0.0933, 0.8710, 0.1145, 0.4189]])
The shape of tensor is: torch.Size([3, 4])
Datatype of tensor is: torch.float32
Device which tensor is stored on: cpu


### Manipulating tensors (tensor operations)
#### Basic operataions

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [ ]:
# Substract and ressigned
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassigned
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
# Can also use torch function
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Original tensor is steel unchanged
tensor

tensor([1, 2, 3])

In [ ]:
# Element-wise multiplication (each element multiplies it's equivalent, index 0->0, 1->1, 2->2)
print(tensor, '*', tensor)
print('Equal: ', tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal:  tensor([1, 4, 9])


### Matrix multiplication (is all you need)

In [1]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [2]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [3]:
%%time
# Matrix multiplication
torch.matmul(tensor, tensor)

CPU times: user 1.36 ms, sys: 0 ns, total: 1.36 ms
Wall time: 7.46 ms


tensor(14)

In [4]:
%%time
# Can also use "@' for matrix multiplication (though not recommended)
tensor @ tensor

CPU times: user 510 µs, sys: 0 ns, total: 510 µs
Wall time: 384 µs


tensor(14)

In [5]:
%%time
# Matrix multiplication by hand
# (Avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 874 µs, sys: 702 µs, total: 1.58 ms
Wall time: 3.89 ms


tensor(14)

### One of the most common errors in deep learning (shape errors)

In [6]:
# Shape needs to be in the right way
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 8], [9, 10], [11, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (This will produce error)

RuntimeError: ignored

In [7]:
# View tensor A & B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [8]:
# View tensor_a and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])


In [9]:
# The opertaion works when tensor_B is transpose
print(f"Original shapes: teansor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimesion match\n")
print('Output\n')
Output = torch.matmul(tensor_A, tensor_B.T)
print(Output)
print(f"\nOutput shape: {Output.shape}")

Original shapes: teansor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimesion match

Output

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

Output shape: torch.Size([3, 3])


In [10]:
# torch.mm is shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

### Finding the min, max, mean, sum, etc (aggregation)

In [11]:
# Craete a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") this will error
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [13]:
# You can use torch built-in method
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)
#torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

#### Positional min/max

In [14]:
# Create tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Return index of max and min
print(f"Index where max value occure: {tensor.argmax()}")
print(f"Index where min value occure: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occure: 8
Index where min value occure: 0


#### Change tensor datatype

In [15]:
# Craete a tensor and check it's datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [16]:
# Create a float16 tensor
tensor_16 = tensor.type(torch.float16)
tensor_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [17]:
# Create a int8 tensor
tensor_8 = tensor.type(torch.int8)
tensor_8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

#### Reshaping, stackingg, squeezing, and unsqueezing

In [18]:
import numpy as np
import torch

In [19]:
# Create tensor
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [20]:
# A dd extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [21]:
# Changes view (keep data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [22]:
# Changes z, changes x
z[0] = torch.arange(1, 8)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [23]:
# Stacked tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [24]:
print(f"Previuos tensor {x_reshaped}")
print(f"Previou shape {x_reshaped.shape}")

# Remove extra dimension from x_reshape
x_squeeze = x_reshaped.squeeze()
print(f"New tensor {x_squeeze}")
print(f"New tensor shape {x_squeeze.shape}")

Previuos tensor tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previou shape torch.Size([1, 7])
New tensor tensor([5., 2., 3., 4., 5., 6., 7.])
New tensor shape torch.Size([7])


In [25]:
print(f"Previous tensor {x_squeeze}")
print(f"Previous Shape {x_squeeze.shape}")

## Add an extra dimension with unsqueeze
x_unsqueeze = x_squeeze.unsqueeze(dim=0)
print(f"\nNew tensor {x_unsqueeze}")
print(f"New shape {x_unsqueeze.shape}")

Previous tensor tensor([5., 2., 3., 4., 5., 6., 7.])
Previous Shape torch.Size([7])

New tensor tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape torch.Size([1, 7])


In [26]:
# Create tensor with a specific shape
x_riginal = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrenge the axis
x_Permute = x_riginal.permute(2, 0, 1)

print(f"previus shape {x_riginal.shape}")
print(f"New shape {x_Permute.shape}")

previus shape torch.Size([224, 224, 3])
New shape torch.Size([3, 224, 224])


#### Indexing (selecting data from tensors)

In [27]:
import torch
import numpy as np

In [28]:
# Create tentsor
y = torch.arange(1, 10).reshape(1, 3, 3)
y, y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [29]:
# Let's index bracket by bracket
print(f"First squire bracket:\n{y[0]}")
print(f"Secoond squire bracket: {y[0][0]}")
print(f"Third squire bracket: {y[0][0][0]}")

First squire bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Secoond squire bracket: tensor([1, 2, 3])
Third squire bracket: 1


In [30]:
# Get all values of 0th dimension and the 0 index of 1st dimension
y[:,0]

tensor([[1, 2, 3]])

In [31]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
y[:, :, 1]

tensor([[2, 5, 8]])

In [32]:
# Get all values of 0th dimension but only the 1 index value of the 1st and 2nd
y[:, 1, 1]

tensor([5])

In [33]:
# Get all values index 0 of 0th and 1st dimension and all values of second dimension
y[0, 0, :] # same as y[0][0]

tensor([1, 2, 3])

### PyTorch tensors & NumPy
The two main method you'll want use for NumPy to PyTorch (and back again) are:
- `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
- `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array

In [34]:
# NumPy arrar to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
tensors = tensor.type(torch.float32)
array, tensor, tensors

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [35]:
# Change array keep the tensor
array += 1
array, tensor, tensors

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [36]:
# Tensor to NumPy
tensor = torch.ones(2, 7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]),
 array([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]], dtype=float32))

In [37]:
# Change the tensor keep the array as the same
tensors = tensor.type(torch.float64)
tensors += 2
tensors, numpy_tensor

(tensor([[3., 3., 3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3., 3., 3.]], dtype=torch.float64),
 array([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]], dtype=float32))

### Reproducibility (Trying to take the random out of random)

In [38]:
# Create tow random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor b:\n{random_tensor_B}\n")
print("Does Tensor A equal tensor B (anywere)?")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.0419, 0.5523, 0.4799, 0.0453],
        [0.4812, 0.1751, 0.7217, 0.0680],
        [0.6042, 0.4335, 0.0134, 0.6836]])

Tensor b:
tensor([[0.3097, 0.4292, 0.2736, 0.5166],
        [0.0427, 0.5916, 0.1848, 0.5412],
        [0.9459, 0.3032, 0.7442, 0.5763]])

Does Tensor A equal tensor B (anywere)?


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [39]:
import torch
import random

# set the random seed
RANDOM_SEED = 42 # try changing this to a differnt values and see what happens
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() function is called
# Without this, tensor_D will be different tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # Try commenting this line out and seeign what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print("Does Tensor C equal Tensor D (anywhere)?")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D (anywhere)?


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [40]:
# Check for GPU
torch.cuda.is_available()

True

In [41]:
# Set device type
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [42]:
# Count number of devices
torch.cuda.device_count()

1

### Nice Practicing the content!!!