<a href="https://colab.research.google.com/github/lurwan2107/ArewaDS_DeepLearning/blob/main/00_PyTorch_Fundamentals_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals Exercises
### 1. Documentation Reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

- The documentation on torch.Tensor.
- The documentation on torch.cuda.

In [3]:
# No code solution (reading)

### 2. Create a random tensor with shape (7, 7).

In [7]:
# Import torch
import torch

# Creating a random tensor
rand_tensor_A = torch.rand(7, 7)
rand_tensor_A, rand_tensor_A.ndim, rand_tensor_A.type # Checking the dimension and the data type.

(tensor([[0.2213, 0.1957, 0.6985, 0.9441, 0.2519, 0.9116, 0.6153],
         [0.2786, 0.5293, 0.2351, 0.0849, 0.5892, 0.9729, 0.3898],
         [0.0866, 0.0915, 0.9247, 0.3391, 0.4261, 0.8808, 0.8685],
         [0.4399, 0.6457, 0.3444, 0.5554, 0.0431, 0.5776, 0.4581],
         [0.9803, 0.7633, 0.4454, 0.2034, 0.5389, 0.1093, 0.0378],
         [0.4078, 0.5599, 0.6854, 0.4672, 0.6415, 0.0657, 0.0230],
         [0.5394, 0.7635, 0.3247, 0.3193, 0.8657, 0.8819, 0.4989]]),
 2,
 <function Tensor.type>)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [8]:
# Creating another random tensor
rand_tensor_B = torch.rand(1, 7)
# Performing matrix multiplication
mat_mult_A = torch.matmul(rand_tensor_A, rand_tensor_B.T)
mat_mult_A

tensor([[1.9270],
        [1.8546],
        [1.9697],
        [1.9384],
        [2.0530],
        [1.4660],
        [2.4042]])

### 4. Set the random seed to 0 and do 2 & 3 over again.

In [25]:
torch.manual_seed(0) # Setting manual seed

# Creating two random tensors
rand_tensor_A = torch.rand(7, 7)
rand_tensor_B = torch.rand(1, 7)

# performing matrix multiplication for the 2 tensors
mat_mult_B = torch.matmul(rand_tensor_A, rand_tensor_B.T)
mat_mult_B, mat_mult_B.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
- If there is, set the GPU random seed to 1234.

In [26]:
# Setting random seed on the GPU
torch.cuda.manual_seed(1234)

Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [27]:
# Setting random seed on the GPU
torch.cuda.manual_seed(1234)

# Checking for access to the GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Creating two random tensors on the GPU
tensor_show_on_gpu_a = torch.rand(2, 3).to(device)
tensor_show_on_gpu_b = torch.rand(2, 3).to(device)

tensor_show_on_gpu_a, tensor_show_on_gpu_b

(tensor([[0.5932, 0.1123, 0.1535],
         [0.2417, 0.7262, 0.7011]], device='cuda:0'),
 tensor([[0.2038, 0.6511, 0.7745],
         [0.4369, 0.5191, 0.6159]], device='cuda:0'))

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [28]:
# Performing matmul on the tensors
mat_mult_C = torch.matmul(tensor_show_on_gpu_a, tensor_show_on_gpu_b.T)
mat_mult_C, mat_mult_C.shape

(tensor([[0.3129, 0.4120],
         [1.0651, 0.9143]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Finding the maximum
print(f"Maximum: {torch.max(mat_mult_C)}")
# Finding the minimum
print(f"Minimum: {torch.min(mat_mult_C)}")

Maximum: 1.0650615692138672
Minimum: 0.31289684772491455


### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Finding arg max
print(f"The maximum value is at index: {mat_mult_C.argmax()}")
# Finding arg min
print(f"The minimum value is at index: {mat_mult_C.argmin()}")

The maximum value is at index: 2
The minimum value is at index: 0


### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [36]:
# Setting the seed
torch.manual_seed(7)

# Creating random tensor
tensor_rand = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
squeezed_tensor = tensor_rand.squeeze()

# Print out tensors and their shapes
print(f"Original Tensor:\n{tensor_rand}\n{tensor_rand.shape}")
print(f"\nModified Tensor:\n{squeezed_tensor}\n{squeezed_tensor.shape}")


Original Tensor:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])

Modified Tensor:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
